### ISSUE TITLE
Guess tape format

### ISSUE THREAD

**Issue by larsbrinkhoff** [larsbrinkhoff/pdp10-its-disassembler#36]
@eswenson1 [wrote](https://github.com/PDP-10/itstar/pull/9#issuecomment-531968596):

> What I'd like to have is a utility, given a tape image filename as a parameter, that would tell you what kind of tape it was (7 or 9 track), big endian or not, ITS or XX, backup or otherwise, etc.

Yes, that would be good.

I imagine a few simple checks should be able to do it:
- Read first 32 bits.  Are they a reasonable record size?
- If not, is it big endian?
- Read the first record.  Is it terminated by the same record size?
- Does the record need padding before the record size?
- Does the record data match 7-track encoding with six bits + parity in every frame?
- Is the first record 1024 words (5120 or 6144 frames) and have a header that looks like DUMP?

@rcornwell any inputs?

**Comment by larsbrinkhoff** [comment]
This should be easy to do in Scala.

**Comment by larsbrinkhoff** [comment]
@ams seems to have a need for this too.  What kind of tape image file begins like this?

```
86 E9 0A 45 0F 3C 00 00  00 00 00 00 00 00 01 00

**Comment by larsbrinkhoff** [comment]
This tools would be quite crucial *if*, purely theoretically you see, someone were to come into contact with, say, hundreds or thousands of tape images and wanted to list their contents.  It's not really feasible to manually categorize the type of image file and type of dump format.

**Comment by larsbrinkhoff** [comment]
@eswenson1, you haven't started anything have you?  I'm considering a Lisp implementation.  Not just to classify tapes, but to interactively examine and modify tape images.  I'm thinking more toolbox than a single use program.

**Comment by eswenson1** [comment]
No. I haven’t looked at this yet.

**Comment by larsbrinkhoff** [comment]
I started a new Lisp project for this:  
http://github.com/larsbrinkhoff/tape-lab

**Comment by eswenson1** [comment]
Not a lot of code there yet, huh?  On what OS do you intend for this code to run?  In which LISP dialect?

**Comment by larsbrinkhoff** [comment]
I have written some code, but then I started rewriting it, and it's not
ready for public consumption yet.

I'm using SBCL, but I'm just doing plain Lisp file I/O.  The major
concern would be memory space since I'm reading the whole image file
into an (unsigned-byte 8) array.

**Comment by ams** [comment]
I've got some code to process some tape formats too. Memory shouldn't be an issue.  In the worst case, it would be trivial to dump a core that you can run individually on a tape basis.

**Comment by ams** [comment]
FWIW, the code already works for LMFL tapes.

**Comment by larsbrinkhoff** [comment]
Ok for you impatient folks, I pushed some code to the tape-lab repository.  No actual guessing yet.

**Comment by eswenson1** [comment]
Why don’t you use streams instead of reading the whole tape into memory?

**Comment by larsbrinkhoff** [comment]
I want to be able to easily go back and forth over the data.  This isn't just for guessing the format, but also analyze errors, fix broken tapes, extract damaged data.
