### ISSUE TITLE
or/nop vs. ior/jfcl

### ISSUE THREAD

**Issue by atsampson** [larsbrinkhoff/pdp10-its-disassembler#59]
434-437 instructions are disassembled as `or`. `ior` seems to be the preferred mnemonic for this in programs; the DEC 1982 Processor Reference mentions OR only as an alias for IOR, and MIDAS doesn't understand it at all.

Similarly, 25500 is disassembled as `nop`; it's usually written as `jfcl` in programs, although there are a couple on ITS that define a `nop` macro themselves.

**Comment by larsbrinkhoff** [comment]
I agree or and jfcl should probably be preferred.  It's something that have been grating my eyes for a while.

Simlilar but less clear would be halt vs jrst 4,.  DEC and MACRO-10 seem to prefer HALT, but it's unknown to MIDAS.

To digress even more, it might be desirable to have a MIDAS output mode where octal addresses and instructions are omitted, text is upper case, etc.
